package com.github.hummel.drealm.init;

import lotr.common.LOTRMod;
import lotr.common.world.structure.LOTRChestContents;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemStack;
import net.minecraft.util.WeightedRandomChestContent;

@SuppressWarnings({"WeakerAccess", "PublicField"})
public class ChestContents {
	public static LOTRChestContents redDwarfHouseLarder;
	public static LOTRChestContents redMountainsStronghold;
	public static LOTRChestContents redMountainsSmithy;
	public static LOTRChestContents windDwarfHouseLarder;
	public static LOTRChestContents windMountainsStronghold;
	public static LOTRChestContents windMountainsSmithy;

	private ChestContents() {
	}

	public static void onInit() {
		redDwarfHouseLarder = new LOTRChestContents(2, 5, new WeightedRandomChestContent[]{new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.bread), 1, 3, 100), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_porkchop), 1, 2, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_beef), 1, 2, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.muttonCooked), 1, 2, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_chicken), 1, 3, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_fished), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.gammon), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.deerCooked), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.mug), 1, 3, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.aleHorn), 1, 2, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.gobletWood), 1, 3, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.gobletGold), 1, 3, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.ceramicPlate), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.woodPlate), 1, 2, 50)});
		redMountainsStronghold = new LOTRChestContents(3, 5, new WeightedRandomChestContent[]{new WeightedRandomChestContent(new ItemStack(Items.helmetRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.bodyRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.legsRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.bootsRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.swordRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.spearRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.battleaxeRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.daggerRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.hammerRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.pikeRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.pickaxeRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.mattockRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.throwingAxeRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.boarArmorRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.coal), 1, 3, 100), new WeightedRandomChestContent(new ItemStack(Blocks.torch), 2, 4, 100), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.iron_ingot), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.ironNugget), 1, 6, 25), new WeightedRandomChestContent(new ItemStack(Items.redDwarfSteel), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.mug), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.aleHorn), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.gobletWood), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_porkchop), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_chicken), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_beef), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.muttonCooked), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.deerCooked), 1, 1, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.gammon), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.compass), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.dwarvenRing), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.mithrilBook), 1, 1, 15)});
		redMountainsSmithy = new LOTRChestContents(3, 4, new WeightedRandomChestContent[]{new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.coal), 1, 4, 100), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.coal, 1, 1), 1, 4, 100), new WeightedRandomChestContent(new ItemStack(LOTRMod.rock, 1, 3), 1, 8, 50), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.iron_ingot), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.ironNugget), 1, 6, 10), new WeightedRandomChestContent(new ItemStack(Items.redDwarfSteel), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.bronze), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.copper), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.tin), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.silver), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.bucket), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_porkchop), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_chicken), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_beef), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.muttonCooked), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.gammon), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.deerCooked), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.bread), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.mithrilBook), 1, 1, 15)});
		windDwarfHouseLarder = new LOTRChestContents(2, 5, new WeightedRandomChestContent[]{new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.bread), 1, 3, 100), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_porkchop), 1, 2, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_beef), 1, 2, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.muttonCooked), 1, 2, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_chicken), 1, 3, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_fished), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.gammon), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.deerCooked), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.mug), 1, 3, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.aleHorn), 1, 2, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.gobletWood), 1, 3, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.gobletGold), 1, 3, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.ceramicPlate), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.woodPlate), 1, 2, 50)});
		windMountainsStronghold = new LOTRChestContents(3, 5, new WeightedRandomChestContent[]{new WeightedRandomChestContent(new ItemStack(Items.helmetWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.bodyWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.legsWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.bootsWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.swordWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.spearWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.battleaxeWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.daggerWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.hammerWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.pikeWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.pickaxeWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.mattockWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.throwingAxeWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.boarArmorWindDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.coal), 1, 3, 100), new WeightedRandomChestContent(new ItemStack(Blocks.torch), 2, 4, 100), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.iron_ingot), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.ironNugget), 1, 6, 25), new WeightedRandomChestContent(new ItemStack(Items.windDwarfSteel), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.mug), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.aleHorn), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.gobletWood), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_porkchop), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_chicken), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_beef), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.muttonCooked), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.deerCooked), 1, 1, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.gammon), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.compass), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.dwarvenRing), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.mithrilBook), 1, 1, 15)});
		windMountainsSmithy = new LOTRChestContents(3, 4, new WeightedRandomChestContent[]{new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.coal), 1, 4, 100), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.coal, 1, 1), 1, 4, 100), new WeightedRandomChestContent(new ItemStack(LOTRMod.rock, 1, 3), 1, 8, 50), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.iron_ingot), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.ironNugget), 1, 6, 10), new WeightedRandomChestContent(new ItemStack(Items.windDwarfSteel), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.bronze), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.copper), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.tin), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.silver), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.bucket), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_porkchop), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_chicken), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.cooked_beef), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.muttonCooked), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.gammon), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.deerCooked), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(net.minecraft.init.Items.bread), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.mithrilBook), 1, 1, 15)});
	}
}